### POST SIGNUP
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "email": "david1@prueba.com",
  "password": "pass"
}
###
### POST SIGNIN
POST http://localhost:3000/api/signin
Content-Type: application/json

{
  "email": "david1@prueba.com",
  "password": "pass"
}
###
### GET PUBLIC TASKS
GET http://localhost:3000/api/tasks

###
### GET PRIVATE TASKS
GET http://localhost:3000/api/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTMyZDFiNzBmMDAzMWFiMzUyMjM2OGYiLCJpYXQiOjE2MzA3MjEwNDl9.ZjlvYFcRtAs3GPAzUpJfxDTFpzfLQJN0XGhlXlgu6mI
###
